### ISSUE TITLE
debug 调试

### ISSUE THREAD

**Issue by zhoufaming** [farmer-hutao/k8s-source-code-analysis#4]
请问下 如何通过写死启动参数 来调试kube-scheduler？

**Comment by daniel-hutao** [comment]
后面会专门讲到debug；
可以加我微信ITNT01，我提前和你说

**Comment by navono** [comment]
如果先把调试方法放在前面说，那么在阅读后续的章节就可以手动去修改源码，然后调试立即得到反馈。这样就可以边阅读这里面相关的章节，边调试去理解整个执行流。

**Comment by daniel-hutao** [comment]
@navono 这周计划增加debug部分；会放到环境搭建后面，可以供大家自己选择何时开始debug
