### ISSUE TITLE
【goland调试问题】

### ISSUE THREAD

**Issue by zoux86** [farmer-hutao/k8s-source-code-analysis#6]
您好。我看您在 debug.md中说你的 goland和k8s集群不在一个机器中。
![image](https://user-images.githubusercontent.com/14087435/55207634-eddd3980-5215-11e9-8ada-6e3a0514325e.png)
最近学习您的项目时，我用的也是 goland，并且我的k8s集群是Ubuntu 服务器。而goland是本机windows电脑。我在goland上装了 “remote hosts access” 感觉这个只是同步我本机和K8s集群的文件。并不能进行远程debug. 
所以，我想请问一下，您是怎样使用goland调试k8s集群的代码呢？

**Comment by daniel-hutao** [comment]
我在微信中收到过同一个问题，应该也是你发的吧？如果问题已经解决了，可以关闭这个issue哈～

**Comment by zoux86** [comment]
微信上是我发的。网上查到一种方法，但是因为这周末服务器那边停电，还没尝试。那这个问题我先关了。
